### ISSUE TITLE
Disappearing Macro Hotbar [BUG]

### ISSUE THREAD

**Issue by joshscorcher** [arcanistzed/sidebar-macros#9] opened 2022-01-07 01:27 UTC
**Describe the bug**
The macro hotbar disappears when a macro is moved or added to the hotbar and must be refreshed in order to reappear.

**To Reproduce**

1. Go to a character sheet.
2. Click and hold any rollable item like weapon or spell
3. Drag to hotbar
4. Hotbar Disappears.

**Details**
Foundry VTT version: Latest Stable
Module version: Latest

**Additional context**
Playing Pathfinder 2e. Maybe conflicts with Drag Anything to Hotbar or Minimal UI modules?

**Comment by arcanistzed** [comment] 2022-01-10 00:36
I can't reproduce this. Could you please narrow it down with Find the Culprit?
Does this happen with only Sidebar Macros enabled?

**Comment by arcanistzed** [comment] 2022-01-10 00:48
Nevermind. I figured it out. Seems like an issue with Minimal UI though

**Comment by arcanistzed** [comment] 2022-01-10 23:58
Fixed by Minimal UI https://github.com/saif-ellafi/foundryvtt-minimal-ui/commit/c4a5b583da06c3f34a3d1495487747848b59f05a

**Closed by arcanistzed** 2022-01-10 23:58 UTC
Labels: bug
